
[2019.11.13 - 10:14:26]
Argument 00 = '192.168.100.99' (used_default: False)
Argument 01 = 'test_user@example.com' (used_default: False)
Argument 02 = '****' (used_default: False)
Argument 03 = 'downloadsnapshots' (used_default: False)
Argument 04 = 'nfs' (used_default: False)
Argument 05 = '\\UniverseNAS\camera\ulo\_snapshots' (used_default: False)
Argument 06 = '100' (used_default: False)
Argument 07 = '480' (used_default: False)
Argument 08 = 'camera' (used_default: False)
Argument 09 = '****' (used_default: False)
Argument 10 = '' (used_default: True)
Argument 11 = '' (used_default: True)


[2019.11.13 - 10:14:27]
Failed. (Error: Error connecting to remote share due to connection already existing (code: '1219'). Hint: If you use same connection within windows, this error will occure. If you use IP in windows, try using host in this connection and vice versa.)
Failed. (Error: Error connecting to remote share due to connection already existing (code: '1219'). Hint: If you use same connection within windows, this error will occure. If you use IP in windows, try using host in this connection and vice versa.)
Failed. (Error: Error connecting to remote share due to connection already existing (code: '1219'). Hint: If you use same connection within windows, this error will occure. If you use IP in windows, try using host in this connection and vice versa.)
Failed. (Error: Error connecting to remote share due to connection already existing (code: '1219'). Hint: If you use same connection within windows, this error will occure. If you use IP in windows, try using host in this connection and vice versa.)
Failed. (Error: Error connecting to remote share due to connection already existing (code: '1219'). Hint: If you use same connection within windows, this error will occure. If you use IP in windows, try using host in this connection and vice versa.)
